BOT_TOKEN = '6901873752:AAHFfqd0ecmY_2wEdUCZ7bhJutiRTe40Bvs'
state = {}

GROUP1 = 'Б05-308'
GROUP2 = 'Б05-302'

MONDAY = 'понедельник'
TUESDAY = 'вторник'
WEDNESDAY = 'среда'
THURSDAY = 'четверг'
FRIDAY = 'пятница'
SATURDAY = 'суббота'
SUNDAY = 'воскресенье'

TIME0_BEGIN = '00:00:00'
TIME0_END = '23:59:59'
TIME1_BEGIN = '09:00:00'
TIME1_END = '10:25:00'
TIME2_BEGIN = '10:45:00'
TIME2_END = '12:10:00'
TIME3_BEGIN = '12:20:00'
TIME3_END = '13:45:00'
TIME4_BEGIN = '13:55:00'
TIME4_END = '15:20:00'
TIME5_BEGIN = '15:30:00'
TIME5_END = '16:55:00'
TIME6_BEGIN = '17:05:00'
TIME6_END = '18:30:00'
TIME7_BEGIN = '18:35:00'
TIME7_END = '20:00:00'

TIME_ARRAY = [TIME1_BEGIN,TIME2_BEGIN,TIME3_BEGIN,TIME4_BEGIN,TIME5_BEGIN,TIME6_BEGIN,TIME7_BEGIN]

REST = 'Пар сейчас нет'
BREAK = 'Перерыв'
FOREIGN_LANGUAGE = 'Иностранный язык'
SAFETY = 'Безопасность жизнедеятельности'
PYTHON = 'Практикум Python'
PE = 'Физическая культура'
SEMINAR_PHYSICS = 'Семинар по общей физике'
LECTURE_PHYSICS = 'Лекция по общей физике'
LABORATORY_WORK = 'Лабораторная работа'
SEMINAR_C = 'Семинар по С++'
LECTURE_C = 'Лекция по С++'
SEMINAR_ALGORITHM = 'Семинар по алгоритмам'
LECTURE_ALGORITHM = 'Лекция по алгоритмам'
SEMINAR_MATAN = 'Семинар по математическому анализу'
LECTURE_MATAN = 'Лекция по математическому анализу'
SEMINAR_GEOMETRY = 'Семинар по аналитической геометрии'
LECTURE_GEOMETRY = 'Лекция по аналитической геометрии'
SEMINAR_COMBINATORICS = 'Семинар по АЛКТГ'
LECTURE_COMBINATORICS = 'Лекция по АЛКТГ'
