import telebot
from telebot import types
import sqlite3
from constants import *

connect = sqlite3.connect('timetable.db')
cursor = connect.cursor()
cursor.execute('CREATE TABLE IF NOT EXISTS timetable ('
               'id INTEGER PRIMARY KEY AUTOINCREMENT,'
               'group_name TEXT,'
               'day_of_week TEXT,'
               'start_time TEXT,'
               'end_time TEXT,'
               'lesson TEXT)')
insert_query = 'INSERT INTO timetable (group_name, day_of_week, start_time, end_time, lesson) VALUES (?, ?, ?, ?, ?)'
data_to_insert = [
    (GROUP2, MONDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, MONDAY, TIME1_BEGIN, TIME1_END, LABORATORY_WORK),
    (GROUP2, MONDAY, TIME1_END, TIME2_BEGIN, BREAK),
    (GROUP2, MONDAY, TIME2_BEGIN, TIME2_END, LABORATORY_WORK),
    (GROUP2, MONDAY, TIME2_END, TIME3_BEGIN, BREAK),
    (GROUP2, MONDAY, TIME3_BEGIN, TIME3_END, SEMINAR_COMBINATORICS),
    (GROUP2, MONDAY, TIME3_END, TIME4_BEGIN, REST),
    (GROUP2, MONDAY, TIME4_BEGIN, TIME4_END, REST),
    (GROUP2, MONDAY, TIME4_END, TIME5_BEGIN, REST),
    (GROUP2, MONDAY, TIME5_BEGIN, TIME5_END, FOREIGN_LANGUAGE),
    (GROUP2, MONDAY, TIME5_END, TIME6_BEGIN, BREAK),
    (GROUP2, MONDAY, TIME6_BEGIN, TIME6_END, SAFETY),
    (GROUP2, MONDAY, TIME6_END, TIME7_BEGIN, BREAK),
    (GROUP2, MONDAY, TIME7_BEGIN, TIME7_END, PYTHON),
    (GROUP2, MONDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, TUESDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, TUESDAY, TIME1_BEGIN, TIME1_END, PE),
    (GROUP2, TUESDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, TUESDAY, TIME2_BEGIN, TIME2_END, REST),
    (GROUP2, TUESDAY, TIME2_END, TIME3_BEGIN, REST),
    (GROUP2, TUESDAY, TIME3_BEGIN, TIME3_END, SEMINAR_PHYSICS),
    (GROUP2, TUESDAY, TIME3_END, TIME4_BEGIN, BREAK),
    (GROUP2, TUESDAY, TIME4_BEGIN, TIME4_END, SEMINAR_C),
    (GROUP2, TUESDAY, TIME4_END, TIME5_BEGIN, BREAK),
    (GROUP2, TUESDAY, TIME5_BEGIN, TIME5_END, SEMINAR_ALGORITHM),
    (GROUP2, TUESDAY, TIME5_END, TIME6_BEGIN, BREAK),
    (GROUP2, TUESDAY, TIME6_BEGIN, TIME6_END, SEMINAR_ALGORITHM),
    (GROUP2, TUESDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, TUESDAY, TIME7_BEGIN, TIME7_END, REST),
    (GROUP2, TUESDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, WEDNESDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, WEDNESDAY, TIME1_BEGIN, TIME1_END, REST),
    (GROUP2, WEDNESDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, WEDNESDAY, TIME2_BEGIN, TIME2_END, LECTURE_MATAN),
    (GROUP2, WEDNESDAY, TIME2_END, TIME3_BEGIN, BREAK),
    (GROUP2, WEDNESDAY, TIME3_BEGIN, TIME3_END, LECTURE_GEOMETRY),
    (GROUP2, WEDNESDAY, TIME3_END, TIME4_BEGIN, BREAK),
    (GROUP2, WEDNESDAY, TIME4_BEGIN, TIME4_END, LECTURE_ALGORITHM),
    (GROUP2, WEDNESDAY, TIME4_END, TIME5_BEGIN, REST),
    (GROUP2, WEDNESDAY, TIME5_BEGIN, TIME5_END, REST),
    (GROUP2, WEDNESDAY, TIME5_END, TIME6_BEGIN, REST),
    (GROUP2, WEDNESDAY, TIME6_BEGIN, TIME6_END, REST),
    (GROUP2, WEDNESDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, WEDNESDAY, TIME7_BEGIN, TIME7_END, REST),
    (GROUP2, WEDNESDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, THURSDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, THURSDAY, TIME1_BEGIN, TIME1_END, FOREIGN_LANGUAGE),
    (GROUP2, THURSDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, THURSDAY, TIME2_BEGIN, TIME2_END, REST),
    (GROUP2, THURSDAY, TIME2_END, TIME3_BEGIN, REST),
    (GROUP2, THURSDAY, TIME3_BEGIN, TIME3_END, REST),
    (GROUP2, THURSDAY, TIME3_END, TIME4_BEGIN, REST),
    (GROUP2, THURSDAY, TIME4_BEGIN, TIME4_END, LECTURE_PHYSICS),
    (GROUP2, THURSDAY, TIME4_END, TIME5_BEGIN, BREAK),
    (GROUP2, THURSDAY, TIME5_BEGIN, TIME5_END, LECTURE_C),
    (GROUP2, THURSDAY, TIME5_END, TIME6_BEGIN, REST),
    (GROUP2, THURSDAY, TIME6_BEGIN, TIME6_END, REST),
    (GROUP2, THURSDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, THURSDAY, TIME7_BEGIN, TIME7_END, LECTURE_ALGORITHM),
    (GROUP2, THURSDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, FRIDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, FRIDAY, TIME1_BEGIN, TIME1_END, PE),
    (GROUP2, FRIDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, FRIDAY, TIME2_BEGIN, TIME2_END, REST),
    (GROUP2, FRIDAY, TIME2_END, TIME3_BEGIN, REST),
    (GROUP2, FRIDAY, TIME3_BEGIN, TIME3_END, LECTURE_MATAN),
    (GROUP2, FRIDAY, TIME3_END, TIME4_BEGIN, BREAK),
    (GROUP2, FRIDAY, TIME4_BEGIN, TIME4_END, SEMINAR_MATAN),
    (GROUP2, FRIDAY, TIME4_END, TIME5_BEGIN, BREAK),
    (GROUP2, FRIDAY, TIME5_BEGIN, TIME5_END, SEMINAR_MATAN),
    (GROUP2, FRIDAY, TIME5_END, TIME6_BEGIN, BREAK),
    (GROUP2, FRIDAY, TIME6_BEGIN, TIME6_END, SEMINAR_GEOMETRY),
    (GROUP2, FRIDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, FRIDAY, TIME7_BEGIN, TIME7_END, REST),
    (GROUP2, FRIDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, SATURDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, SATURDAY, TIME1_BEGIN, TIME1_END, REST),
    (GROUP2, SATURDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, SATURDAY, TIME2_BEGIN, TIME2_END, REST),
    (GROUP2, SATURDAY, TIME2_END, TIME3_BEGIN, REST),
    (GROUP2, SATURDAY, TIME3_BEGIN, TIME3_END, REST),
    (GROUP2, SATURDAY, TIME3_END, TIME4_BEGIN, REST),
    (GROUP2, SATURDAY, TIME4_BEGIN, TIME4_END, REST),
    (GROUP2, SATURDAY, TIME4_END, TIME5_BEGIN, REST),
    (GROUP2, SATURDAY, TIME5_BEGIN, TIME5_END, REST),
    (GROUP2, SATURDAY, TIME5_END, TIME6_BEGIN, REST),
    (GROUP2, SATURDAY, TIME6_BEGIN, TIME6_END, REST),
    (GROUP2, SATURDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, SATURDAY, TIME7_BEGIN, TIME7_END, REST),
    (GROUP2, SATURDAY, TIME7_END, TIME0_END, REST),

    (GROUP2, SUNDAY, TIME0_BEGIN, TIME1_BEGIN, REST),
    (GROUP2, SUNDAY, TIME1_BEGIN, TIME1_END, REST),
    (GROUP2, SUNDAY, TIME1_END, TIME2_BEGIN, REST),
    (GROUP2, SUNDAY, TIME2_BEGIN, TIME2_END, REST),
    (GROUP2, SUNDAY, TIME2_END, TIME3_BEGIN, REST),
    (GROUP2, SUNDAY, TIME3_BEGIN, TIME3_END, REST),
    (GROUP2, SUNDAY, TIME3_END, TIME4_BEGIN, REST),
    (GROUP2, SUNDAY, TIME4_BEGIN, TIME4_END, REST),
    (GROUP2, SUNDAY, TIME4_END, TIME5_BEGIN, REST),
    (GROUP2, SUNDAY, TIME5_BEGIN, TIME5_END, REST),
    (GROUP2, SUNDAY, TIME5_END, TIME6_BEGIN, REST),
    (GROUP2, SUNDAY, TIME6_BEGIN, TIME6_END, REST),
    (GROUP2, SUNDAY, TIME6_END, TIME7_BEGIN, REST),
    (GROUP2, SUNDAY, TIME7_BEGIN, TIME7_END, REST),
    (GROUP2, SUNDAY, TIME7_END, TIME0_END, REST),
]
cursor.executemany(insert_query, data_to_insert)
connect.commit()
cursor.close()
connect.close()
